CREATE TABLE OSCUSTOM_USERS(
     USERNAME VARCHAR2(15) NOT NULL,
     USER_PASSWORD VARCHAR2 (20) NOT NULL,
     FIRST_NAME VARCHAR2 (30) NOT NULL,
     LAST_NAME VARCHAR2 (30) NOT NULL,
     EMAIL VARCHAR2 (50) ,
     ACCOUNT_STATUS VARCHAR2(10) ,
     NUM_INVALID_LOGINS NUMBER ,
     CLIENT_ID    VARCHAR2(50),
     ACCESS_CODE	CHAR(1),
     PRIMARY KEY(USERNAME))
     
     
    INSERT INTO OSCUSTOM_USERS  
     VALUES( 'USER_01', 'Password123', 'Manish', 'Mohan', 'manish@gmail.com', 'UNLOCKED', 0,'CLIENT1','A');
     
      INSERT INTO OSCUSTOM_USERS  
     VALUES( 'USER_02', 'Password123', 'Manish1', 'Mohan', 'manish1@gmail.com', 'UNLOCKED', 0,'CLIENT1','A');
     
     
     CREATE TABLE OSCUSTOM_CLIENTS(
     CLIENT_ID	VARCHAR2(50),
     CLIENT_NAME	VARCHAR2(100),
     ACTIVE		CHAR(1),
     SHIPPING_ID	VARCHAR2(50),
     PRIMARY KEY ( CLIENT_ID))
     
     
     select CLIENT_NAME,CLIENT_ID from OSCUSTOM_CLIENTS